/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RobotCore1Framework                    */
/*      FILE         :  RobotCore1Framework.cpp                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX63T                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              

//#include "typedefine.h"
#include "../UserApplication/App.h"

#include "..\Modules\micon\iodefine.h"
#include "..\Modules\micon\SCIc.h"

#include "..\Modules\Motor.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

/**
 *  メイン関数
 */
void main(void)
{
	Initialize();


	while(true)
	{
		_Motor_Loop();

		MainLoop();
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
