/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RobotCore1Framework                    */
/*      FILE         :  RobotCore1Framework.cpp                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX63T                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              

//#include "typedefine.h"
#include "../UserApplication/App.h"

#include "BatteryCheck.h"

#include "..\Modules\Timer.h"
#include "..\Modules\Motor.h"
#include "..\Modules\Battery.h"
#include "..\Modules\LED.h"
#include "..\Modules\Buzzer.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
static void Timer1_Caooback(void);
}
#endif

/**
 *  メイン関数
 */
void main(void)
{
	_LED_Activate();

	Initialize();

	_Battery_Activate();

	_Timer_Activate();
	_Timer1_Set(TimerClock_32, 10000, Timer1_Caooback);
	_Timer1_Start();

	while(true)
	{
		MainLoop();
	}
}

void Timer1_Caooback()
{
	BatteryCheck();
	_Motor_Loop();
	_Battery_Sample();
	_Buzzer_Loop();
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
